version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "glab"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "admin456"
      MYSQL_ROOT_PASSWORD: "admin123"

  phpmyadmin:
    image: phpmyadmin
    container_name: "dev_phpmyadmin"
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306